export const TYPES = {
  PENDING: 'FETCH_PENDING_JP_PLACEHOLDER',
  FIND: 'FETCH_SUCCESS_JP_PLACEHOLDER',
  LIST: 'FETCH_LIST_SUCCESS_JP_PLACEHOLDER',
  UPDATE: 'FETCH_UPDATE_SUCCESS_JP_PLACEHOLDER',
  ERROR: 'FETCH_ERROR_JP_PLACEHOLDER',
};
